### ISSUE TITLE
Checkbox instead of Switch

### ISSUE THREAD

**Issue by mcooper7290** [tehapo/Switch#6]
When I use Switch I see a simple basic CheckBox instead of Switch.

Here is the use:

Switch sw = new Switch("SWITCH", valueBool);

Screenshot of result is attached.

I'm using Switch 2.0.3 with Vaadin 7.5.7

![image](https://cloud.githubusercontent.com/assets/1441386/11852307/0d9d3922-a3ec-11e5-81b5-fa1e02e8cde7.png)

**Comment by tehapo** [comment]
This happens when your compiled widgetset does not include the client-side code of Switch. You should check your setup for widgetset compilation.

For more info see: https://github.com/tehapo/Switch/issues/4
